### ISSUE TITLE
Enlaces genéricos en app

### ISSUE THREAD

**Issue by cesarpalacios** [ealejandro101/cohortes#5]
Los enlaces deben coger la ruta antes del enlace automáticamente es decir: 

tenemos http://enlace/cohortes/

si ingresamos un nueva rama dentro de la dirección debería esta identificar automáticamente la ruta es decir: 

- http://enlace/nuevarama/cohortes/

Así funcionara sin problemas el sistema.

**Comment by DanielJaramillo94** [comment]
Issue transladado a *cohortes-admin* ([ver repositorio](https://github.com/ealejandro101/cohortes-admin)).
Ver este issue [aquí](https://github.com/ealejandro101/cohortes-admin/issues/40)
